apiVersion: v1
kind: Service
metadata:
  annotations:
  name: ps-billing-lb
  namespace: oteam-mvne-ns
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31779
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: ps-billing
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: LoadBalancer
