apiVersion: v1
kind: Service
metadata:
  annotations:
  name: ps-product-lb
  namespace: oteam-mvne-ns
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32705
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: ps-product
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: LoadBalancer
